import html
import json
from pathlib import Path
from typing import ClassVar

from metagpt.actions import Action

from core.contracts.design_system_schema import (
    DesignSystemContract,
)
from core.contracts.frontend_result_schema import (
    FrontendBuildGate,
    FrontendResult,
    GeneratedFile,
    SkillEvidence,
)
from core.contracts.implementation_plan_schema import (
    ImplementationPlan,
)
from core.contracts.schema import DesignContract
from core.contracts.visual_composition_schema import (
    PageSpec,
    VisualComposition,
)
from core.runtime.workspace_writer import WorkspaceWriter
from core.skills.policy_resolver import SkillPolicyResolver


class GenerateFrontendProjectV2(Action):
    name: str = "GenerateFrontendProjectV2"

    desc: str = (
        "Generate a page-role-specific ecommerce frontend by consuming "
        "Design Contract, Design System, Implementation Plan, "
        "Visual Composition and local skills_UIUX policies."
    )

    TECHNICAL_COPY: ClassVar[tuple[str, ...]] = (
        "generated by",
        "factory placeholder",
        "static github pages entry",
        "uiux factory static",
        "deterministic placeholder",
    )

    @staticmethod
    def resolve_brand(
        design_system: DesignSystemContract,
        contract: DesignContract,
    ) -> tuple[str, str]:
        token = (
            design_system.foundations.colors.get(
                "color.brand.primary"
            )
        )

        if token and token.value:
            return str(token.value), token.status

        family = (
            contract.project.requested_primary_color
            or ""
        ).lower()

        fallback = {
            "purple": "#6C3BEF",
            "orange": "#E36D19",
            "red": "#C8323E",
            "green": "#168A4A",
            "blue": "#2864DC",
            "black": "#15131A",
        }.get(
            family,
            "#6C3BEF",
        )

        return fallback, "factory_default"

    @staticmethod
    def find_page(
        composition: VisualComposition,
        path: str,
    ) -> PageSpec:
        def normalize(value: str) -> str:
            if not value:
                return "/"

            normalized = "/" + value.strip("/")

            if normalized == "/":
                return "/"

            return normalized.lower()

        requested = normalize(path)

        # 1. Exact normalized route.
        for page in composition.pages:
            if normalize(page.path) == requested:
                return page

        # 2. Nested / dynamic route.
        prefix = requested.rstrip("/") + "/"

        for page in composition.pages:
            candidate = normalize(page.path)

            if candidate.startswith(prefix):
                return page

        # 3. Semantic route/page-role aliases.
        aliases = {
            "/category": (
                "category",
                "catalog",
                "catalogue",
                "collection",
                "browse",
                "listing",
                "shop",
                "products",
                "product listing",
            ),
            "/search": (
                "search",
                "find",
                "query",
                "results",
                "search results",
            ),
            "/cart": (
                "cart",
                "basket",
                "bag",
                "shopping cart",
            ),
            "/checkout": (
                "checkout",
                "payment",
                "order",
                "purchase",
                "transaction",
            ),
        }

        keywords = aliases.get(
            requested,
            (),
        )

        for page in composition.pages:
            haystack = " ".join(
                [
                    page.path or "",
                    page.page_role or "",
                    page.composition_family or "",
                ]
            ).lower()

            if any(
                keyword in haystack
                for keyword in keywords
            ):
                return page

        available = [
            {
                "path": page.path,
                "page_role": page.page_role,
                "composition_family": page.composition_family,
            }
            for page in composition.pages
        ]

        raise RuntimeError(
            "Visual Composition missing a route compatible with "
            f"{path}. Available pages: {available}"
        )

    @staticmethod
    def section_types(
        page: PageSpec,
    ) -> set[str]:
        return {
            section.type
            for section in page.sections
        }

    @classmethod
    def require_home_contract(
        cls,
        home: PageSpec,
    ) -> None:
        required = {
            "commerce-header",
            "editorial-product-hero",
            "category-navigation",
            "featured-products",
            "brand-proof",
        }

        missing = required - cls.section_types(
            home
        )

        if missing:
            raise RuntimeError(
                "Visual Composition home contract incomplete. "
                f"Missing: {sorted(missing)}"
            )

    @staticmethod
    def home_html(
        brand_name: str,
    ) -> str:
        return f'''<!doctype html>
<html lang="vi">
<head>
  <meta charset="utf-8">
  <meta
    name="viewport"
    content="width=device-width, initial-scale=1"
  >
  <meta
    name="description"
    content="Sản phẩm công nghệ tuyển chọn cho không gian sống và làm việc hiện đại."
  >
  <title>{html.escape(brand_name)} — Curated technology</title>
  <link rel="stylesheet" href="./assets/site.css">
</head>
<body>
  <div class="announcement">
    <div class="announcement__inner">
      <span>Miễn phí vận chuyển cho đơn từ 799.000₫</span>
      <span class="announcement__secondary">
        Đổi trả 30 ngày · Hỗ trợ 24/7
      </span>
    </div>
  </div>

  <header class="site-header">
    <a
      class="brand"
      href="./"
      aria-label="{html.escape(brand_name)} - Trang chủ"
    >
      <span class="brand__mark" aria-hidden="true">V</span>
      <span>{html.escape(brand_name)}</span>
    </a>

    <nav class="main-nav" aria-label="Điều hướng chính">
      <a href="./category/">Sản phẩm</a>
      <a href="./category/">Bộ sưu tập</a>
      <a href="./category/">Mới về</a>
    </nav>

    <div class="header-actions">
      <a href="./search/">Tìm kiếm</a>
      <a class="cart-link" href="./cart/">
        <span>Giỏ hàng</span>
        <span class="cart-count" aria-label="2 sản phẩm">2</span>
      </a>
    </div>
  </header>

  <main>
    <section class="hero page-shell">
      <div class="hero__content">
        <div class="eyebrow">
          <span class="eyebrow__line"></span>
          <span>Bộ sưu tập 2026</span>
        </div>

        <h1>
          Công nghệ đẹp hơn.
          <span>Trải nghiệm tốt hơn.</span>
        </h1>

        <p class="hero__description">
          Những sản phẩm được chọn lọc cho không gian sống
          và làm việc hiện đại — rõ ràng, tinh tế và dễ dùng mỗi ngày.
        </p>

        <div class="hero__actions">
          <a class="button button--primary" href="./category/">
            Khám phá bộ sưu tập
            <span aria-hidden="true">↗</span>
          </a>

          <a class="text-link" href="#featured">
            Xem sản phẩm nổi bật
          </a>
        </div>

        <dl class="hero-metrics">
          <div>
            <dt>Sản phẩm chọn lọc</dt>
            <dd>120+</dd>
          </div>
          <div>
            <dt>Đánh giá khách hàng</dt>
            <dd>4.9/5</dd>
          </div>
          <div>
            <dt>Giao nhanh nội thành</dt>
            <dd>24h</dd>
          </div>
        </dl>
      </div>

      <div class="hero-product" aria-label="Aurora One">
        <div class="hero-product__meta">
          <span class="badge">Mới</span>
          <span>01 / 03</span>
        </div>

        <div class="headphone" aria-hidden="true">
          <div class="headphone__band"></div>
          <div class="headphone__cup headphone__cup--left"></div>
          <div class="headphone__cup headphone__cup--right"></div>
        </div>

        <div class="hero-product__footer">
          <div>
            <span>Audio</span>
            <strong>Aurora One</strong>
          </div>
          <div class="hero-product__price">
            <span>Từ</span>
            <strong>2.490.000₫</strong>
          </div>
        </div>
      </div>
    </section>

    <section
      class="category-nav"
      aria-labelledby="category-heading"
    >
      <div class="page-shell category-nav__inner">
        <h2 id="category-heading">Khám phá theo danh mục</h2>
        <div class="category-nav__links">
          <a href="./category/">Âm thanh</a>
          <a href="./category/">Workspace</a>
          <a href="./category/">Chiếu sáng</a>
          <a href="./category/">Phụ kiện</a>
        </div>
      </div>
    </section>

    <section
      class="featured page-shell"
      id="featured"
      aria-labelledby="featured-heading"
    >
      <header class="section-heading">
        <div>
          <p class="section-kicker">Nổi bật tuần này</p>
          <h2 id="featured-heading">
            Thiết kế để bạn muốn dùng mỗi ngày.
          </h2>
        </div>

        <a class="text-link" href="./category/">
          Xem tất cả sản phẩm
          <span aria-hidden="true">→</span>
        </a>
      </header>

      <div class="product-grid">
        <article class="product-card product-card--lead">
          <a href="./product/aurora-headphones/">
            <div class="product-media product-media--purple">
              <span class="product-tag">Bestseller</span>
              <div class="mini-headphone" aria-hidden="true">
                <div class="mini-headphone__band"></div>
                <div class="mini-headphone__left"></div>
                <div class="mini-headphone__right"></div>
              </div>
            </div>
            <div class="product-card__info">
              <div>
                <span>Audio</span>
                <h3>Aurora Headphones</h3>
              </div>
              <strong>2.490.000₫</strong>
            </div>
          </a>
        </article>

        <article class="product-card">
          <a href="./product/arc-keyboard/">
            <div class="product-media product-media--sand">
              <span class="product-tag product-tag--light">Mới</span>
              <div class="keyboard-object" aria-hidden="true">
                <i></i><i></i><i></i>
              </div>
            </div>
            <div class="product-card__info">
              <div>
                <span>Workspace</span>
                <h3>Arc Keyboard</h3>
              </div>
              <strong>1.890.000₫</strong>
            </div>
          </a>
        </article>

        <article class="product-card">
          <a href="./product/luma-lamp/">
            <div class="product-media product-media--ice">
              <span class="product-tag product-tag--light">
                Editor's pick
              </span>
              <div class="lamp-object" aria-hidden="true">
                <div class="lamp-object__head"></div>
                <div class="lamp-object__arm"></div>
                <div class="lamp-object__base"></div>
              </div>
            </div>
            <div class="product-card__info">
              <div>
                <span>Lighting</span>
                <h3>Luma Lamp</h3>
              </div>
              <strong>1.290.000₫</strong>
            </div>
          </a>
        </article>
      </div>
    </section>

    <section class="brand-story">
      <div class="page-shell brand-story__grid">
        <div>
          <p class="section-kicker">Violet standard</p>
          <h2>Ít hơn, nhưng tốt hơn.</h2>
          <p>
            Chúng tôi chọn sản phẩm dựa trên ba tiêu chí:
            thiết kế có chủ đích, trải nghiệm rõ ràng
            và giá trị sử dụng lâu dài.
          </p>
          <a class="text-link text-link--inverse" href="./category/">
            Khám phá tiêu chuẩn chọn lọc
            <span aria-hidden="true">→</span>
          </a>
        </div>

        <div class="brand-art" aria-hidden="true">
          <div class="brand-art__orbit brand-art__orbit--a"></div>
          <div class="brand-art__orbit brand-art__orbit--b"></div>
          <div class="brand-art__object"></div>
        </div>
      </div>
    </section>
  </main>

  <footer class="site-footer">
    <div class="page-shell site-footer__inner">
      <div>
        <a class="brand" href="./">
          <span class="brand__mark" aria-hidden="true">V</span>
          <span>{html.escape(brand_name)}</span>
        </a>
        <p>Công nghệ tuyển chọn cho cuộc sống hiện đại.</p>
      </div>

      <nav aria-label="Điều hướng chân trang">
        <a href="./category/">Sản phẩm</a>
        <a href="./search/">Tìm kiếm</a>
        <a href="./cart/">Giỏ hàng</a>
      </nav>
    </div>
  </footer>

  <script src="./assets/site.js"></script>
</body>
</html>
'''

    @staticmethod
    def css(brand: str) -> str:
        return f''':root {{
  --brand: {brand};
  --brand-900: #26133d;
  --brand-100: #efe8ff;
  --surface: #fcfbfd;
  --surface-strong: #ffffff;
  --text: #17131d;
  --text-muted: #6d6675;
  --border: #e8e2ec;
  --content: 1320px;
  --radius-sm: 8px;
  --radius-md: 14px;
  --radius-lg: 26px;
}}

* {{
  box-sizing: border-box;
}}

html {{
  scroll-behavior: smooth;
  background: var(--surface);
  color: var(--text);
  font-family:
    Inter,
    ui-sans-serif,
    system-ui,
    -apple-system,
    BlinkMacSystemFont,
    "Segoe UI",
    sans-serif;
}}

body {{
  margin: 0;
  min-height: 100vh;
}}

a {{
  color: inherit;
  text-decoration: none;
}}

a:focus-visible,
button:focus-visible,
input:focus-visible,
select:focus-visible {{
  outline: 3px solid var(--brand);
  outline-offset: 4px;
}}

.page-shell {{
  width: min(calc(100% - 56px), var(--content));
  margin-inline: auto;
}}

.announcement {{
  color: white;
  background: var(--brand-900);
}}

.announcement__inner {{
  max-width: var(--content);
  margin: 0 auto;
  padding: 9px 28px;
  display: flex;
  justify-content: space-between;
  gap: 24px;
  font-size: .76rem;
}}

.announcement__secondary {{
  color: rgba(255,255,255,.65);
}}

.site-header {{
  max-width: var(--content);
  min-height: 78px;
  margin: 0 auto;
  padding: 0 28px;
  display: grid;
  grid-template-columns: 1fr auto 1fr;
  align-items: center;
  gap: 32px;
  border-bottom: 1px solid var(--border);
}}

.brand {{
  width: max-content;
  display: inline-flex;
  align-items: center;
  gap: 10px;
  font-weight: 850;
  letter-spacing: -.03em;
}}

.brand__mark {{
  width: 32px;
  height: 32px;
  display: grid;
  place-items: center;
  border-radius: 50%;
  color: white;
  background: var(--brand);
  font-size: .78rem;
}}

.main-nav {{
  display: flex;
  gap: 34px;
  font-size: .9rem;
}}

.header-actions {{
  justify-self: end;
  display: flex;
  align-items: center;
  gap: 22px;
  font-size: .88rem;
}}

.cart-link {{
  display: inline-flex;
  align-items: center;
  gap: 8px;
}}

.cart-count {{
  min-width: 22px;
  height: 22px;
  padding: 0 6px;
  display: inline-grid;
  place-items: center;
  border-radius: 999px;
  color: white;
  background: var(--brand);
  font-size: .68rem;
  font-weight: 800;
}}

.hero {{
  min-height: 700px;
  padding-block: 72px 88px;
  display: grid;
  grid-template-columns: .94fr 1.06fr;
  align-items: center;
  gap: 74px;
}}

.eyebrow {{
  display: flex;
  align-items: center;
  gap: 12px;
  color: var(--brand);
  font-size: .72rem;
  font-weight: 850;
  letter-spacing: .14em;
  text-transform: uppercase;
}}

.eyebrow__line {{
  width: 34px;
  height: 1px;
  background: var(--brand);
}}

.hero h1 {{
  max-width: 720px;
  margin: 24px 0 22px;
  font-size: clamp(3.45rem, 5.8vw, 6rem);
  line-height: .96;
  letter-spacing: -.064em;
  font-weight: 760;
}}

.hero h1 span {{
  display: block;
  color: var(--brand);
}}

.hero__description {{
  max-width: 610px;
  color: var(--text-muted);
  font-size: 1.04rem;
  line-height: 1.75;
}}

.hero__actions {{
  margin-top: 34px;
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  gap: 24px;
}}

.button {{
  min-height: 52px;
  padding: 0 22px;
  display: inline-flex;
  align-items: center;
  gap: 14px;
  border: 0;
  border-radius: var(--radius-md);
  font: inherit;
  font-size: .9rem;
  font-weight: 800;
  cursor: pointer;
}}

.button--primary {{
  color: white;
  background: var(--brand);
}}

.text-link {{
  display: inline-flex;
  align-items: center;
  gap: 9px;
  padding-bottom: 4px;
  border-bottom: 1px solid currentColor;
  font-size: .9rem;
  font-weight: 720;
}}

.hero-metrics {{
  margin: 50px 0 0;
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 24px;
}}

.hero-metrics div {{
  padding-top: 16px;
  display: flex;
  flex-direction: column-reverse;
  gap: 5px;
  border-top: 1px solid var(--border);
}}

.hero-metrics dt {{
  color: var(--text-muted);
  font-size: .73rem;
}}

.hero-metrics dd {{
  margin: 0;
  font-size: 1.13rem;
  font-weight: 820;
}}

.hero-product {{
  min-height: 560px;
  padding: 28px;
  display: grid;
  grid-template-rows: auto 1fr auto;
  overflow: hidden;
  border-radius: 30px;
  background: var(--brand-100);
}}

.hero-product__meta,
.hero-product__footer {{
  display: flex;
  justify-content: space-between;
  gap: 24px;
}}

.hero-product__meta {{
  align-items: center;
  color: var(--text-muted);
  font-size: .72rem;
}}

.badge {{
  padding: 7px 10px;
  border-radius: 999px;
  color: white;
  background: var(--brand-900);
  font-size: .63rem;
  font-weight: 850;
  letter-spacing: .08em;
  text-transform: uppercase;
}}

.headphone {{
  position: relative;
  width: 310px;
  height: 320px;
  margin: auto;
}}

.headphone__band {{
  position: absolute;
  left: 50%;
  top: 22px;
  width: 185px;
  height: 224px;
  transform: translateX(-50%);
  border: 30px solid var(--brand-900);
  border-bottom: 0;
  border-radius: 112px 112px 25px 25px;
}}

.headphone__cup {{
  position: absolute;
  bottom: 18px;
  width: 86px;
  height: 128px;
  border-radius: 45px;
  background: var(--brand);
}}

.headphone__cup--left {{
  left: 35px;
}}

.headphone__cup--right {{
  right: 35px;
}}

.hero-product__footer {{
  align-items: end;
}}

.hero-product__footer span {{
  display: block;
  color: var(--text-muted);
  font-size: .7rem;
}}

.hero-product__footer strong {{
  display: block;
  margin-top: 5px;
  font-size: 1.25rem;
}}

.hero-product__price {{
  text-align: right;
}}

.category-nav {{
  border-block: 1px solid var(--border);
  background: var(--surface-strong);
}}

.category-nav__inner {{
  min-height: 84px;
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 30px;
}}

.category-nav h2 {{
  margin: 0;
  color: var(--text-muted);
  font-size: .75rem;
  font-weight: 500;
}}

.category-nav__links {{
  display: flex;
  gap: 38px;
  flex-wrap: wrap;
  font-size: .89rem;
  font-weight: 720;
}}

.featured {{
  padding-block: 112px 124px;
}}

.section-heading {{
  margin-bottom: 38px;
  display: flex;
  justify-content: space-between;
  align-items: end;
  gap: 42px;
}}

.section-kicker {{
  margin: 0 0 11px;
  color: var(--brand);
  font-size: .7rem;
  font-weight: 850;
  letter-spacing: .13em;
  text-transform: uppercase;
}}

.section-heading h2,
.brand-story h2 {{
  max-width: 720px;
  margin: 0;
  font-size: clamp(2.35rem, 4vw, 4.15rem);
  line-height: 1;
  letter-spacing: -.055em;
}}

.product-grid {{
  display: grid;
  grid-template-columns: 1.18fr .91fr .91fr;
  gap: 20px;
}}

.product-media {{
  position: relative;
  aspect-ratio: 4 / 5;
  display: grid;
  place-items: center;
  overflow: hidden;
  border-radius: 22px;
}}

.product-media--purple {{
  background: #eee7ff;
}}

.product-media--sand {{
  background: #f0ebe3;
}}

.product-media--ice {{
  background: #eaf0f5;
}}

.product-tag {{
  position: absolute;
  top: 18px;
  left: 18px;
  padding: 7px 10px;
  border-radius: 999px;
  color: white;
  background: var(--brand-900);
  font-size: .62rem;
  font-weight: 800;
}}

.product-tag--light {{
  color: var(--text);
  background: rgba(255,255,255,.76);
}}

.product-card__info {{
  padding-top: 17px;
  display: flex;
  justify-content: space-between;
  align-items: end;
  gap: 20px;
}}

.product-card__info span {{
  color: var(--text-muted);
  font-size: .68rem;
}}

.product-card__info h3 {{
  margin: 5px 0 0;
  font-size: 1rem;
}}

.product-card__info strong {{
  white-space: nowrap;
  font-size: .88rem;
}}

.mini-headphone {{
  position: relative;
  width: 230px;
  height: 250px;
}}

.mini-headphone__band {{
  position: absolute;
  left: 50%;
  top: 14px;
  width: 150px;
  height: 188px;
  transform: translateX(-50%);
  border: 24px solid var(--brand-900);
  border-bottom: 0;
  border-radius: 98px 98px 22px 22px;
}}

.mini-headphone__left,
.mini-headphone__right {{
  position: absolute;
  bottom: 15px;
  width: 69px;
  height: 103px;
  border-radius: 35px;
  background: var(--brand);
}}

.mini-headphone__left {{
  left: 30px;
}}

.mini-headphone__right {{
  right: 30px;
}}

.keyboard-object {{
  width: 78%;
  padding: 24px 22px;
  display: grid;
  gap: 9px;
  transform: rotate(-8deg);
  border-radius: 17px;
  background: #29252d;
}}

.keyboard-object i {{
  height: 10px;
  border-radius: 4px;
  background:
    repeating-linear-gradient(
      90deg,
      #faf8ff 0 16px,
      transparent 16px 22px
    );
}}

.lamp-object {{
  position: relative;
  width: 190px;
  height: 240px;
}}

.lamp-object__head {{
  position: absolute;
  left: 50%;
  top: 20px;
  width: 112px;
  height: 62px;
  transform: translateX(-50%);
  border-radius: 58px 58px 18px 18px;
  background: var(--brand);
}}

.lamp-object__arm {{
  position: absolute;
  left: 50%;
  top: 74px;
  width: 14px;
  height: 120px;
  transform: translateX(-50%);
  border-radius: 8px;
  background: #32343b;
}}

.lamp-object__base {{
  position: absolute;
  left: 50%;
  bottom: 21px;
  width: 112px;
  height: 23px;
  transform: translateX(-50%);
  border-radius: 50%;
  background: #32343b;
}}

.brand-story {{
  padding-block: 118px;
  color: white;
  background: var(--brand-900);
}}

.brand-story__grid {{
  display: grid;
  grid-template-columns: .86fr 1.14fr;
  gap: 78px;
  align-items: center;
}}

.brand-story p:not(.section-kicker) {{
  max-width: 580px;
  color: rgba(255,255,255,.68);
  line-height: 1.75;
}}

.text-link--inverse {{
  margin-top: 18px;
}}

.brand-art {{
  position: relative;
  min-height: 420px;
  overflow: hidden;
  border-radius: var(--radius-lg);
  background: #1b1028;
}}

.brand-art__orbit {{
  position: absolute;
  left: 50%;
  top: 50%;
  transform: translate(-50%, -50%);
  border: 1px solid rgba(255,255,255,.2);
  border-radius: 50%;
}}

.brand-art__orbit--a {{
  width: 270px;
  height: 270px;
}}

.brand-art__orbit--b {{
  width: 410px;
  height: 410px;
}}

.brand-art__object {{
  position: absolute;
  left: 50%;
  top: 50%;
  width: 108px;
  height: 108px;
  transform: translate(-50%, -50%) rotate(45deg);
  border-radius: 23px;
  background: var(--brand);
}}

.site-footer {{
  background: var(--surface-strong);
  border-top: 1px solid var(--border);
}}

.site-footer__inner {{
  min-height: 180px;
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 40px;
}}

.site-footer p {{
  margin: 13px 0 0;
  color: var(--text-muted);
  font-size: .77rem;
}}

.site-footer nav {{
  display: flex;
  gap: 28px;
  font-size: .84rem;
}}

.route-page {{
  min-height: 72vh;
  padding-block: 86px;
}}

.route-page__heading {{
  max-width: 760px;
}}

.route-page__heading h1 {{
  margin: 12px 0 14px;
  font-size: clamp(2.8rem, 6vw, 5.4rem);
  line-height: .98;
  letter-spacing: -.06em;
}}

.route-page__heading p {{
  color: var(--text-muted);
  line-height: 1.7;
}}

.browse-layout {{
  margin-top: 48px;
  display: grid;
  grid-template-columns: 230px 1fr;
  gap: 38px;
}}

.filter-panel {{
  align-self: start;
  padding-top: 18px;
  border-top: 1px solid var(--border);
}}

.filter-list {{
  display: grid;
  gap: 13px;
  color: var(--text-muted);
  font-size: .86rem;
}}

.browse-grid {{
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 18px;
}}

.compact-product {{
  padding-top: 14px;
  border-top: 1px solid var(--border);
}}

.compact-product__media {{
  aspect-ratio: 4 / 5;
  margin-bottom: 13px;
  border-radius: var(--radius-md);
  background: var(--brand-100);
}}

.compact-product h3 {{
  margin: 0 0 5px;
  font-size: .94rem;
}}

.compact-product p {{
  margin: 0;
  color: var(--text-muted);
  font-size: .8rem;
}}

.transaction-layout {{
  margin-top: 48px;
  display: grid;
  grid-template-columns: 1fr 380px;
  gap: 48px;
}}

.form-stack {{
  display: grid;
  gap: 16px;
}}

.field {{
  display: grid;
  gap: 7px;
}}

.field label {{
  font-size: .8rem;
  font-weight: 700;
}}

.field input {{
  min-height: 48px;
  padding: 0 14px;
  border: 1px solid var(--border);
  border-radius: var(--radius-sm);
  background: white;
  color: var(--text);
  font: inherit;
}}

.summary {{
  align-self: start;
  padding: 24px;
  border: 1px solid var(--border);
  border-radius: var(--radius-md);
  background: white;
}}

@media (max-width: 980px) {{
  .site-header {{
    grid-template-columns: 1fr auto;
  }}

  .main-nav {{
    display: none;
  }}

  .hero {{
    grid-template-columns: 1fr;
    gap: 44px;
  }}

  .product-grid {{
    grid-template-columns: 1fr 1fr;
  }}

  .product-card--lead {{
    grid-column: 1 / -1;
  }}

  .brand-story__grid {{
    grid-template-columns: 1fr;
  }}

  .browse-layout,
  .transaction-layout {{
    grid-template-columns: 1fr;
  }}

  .browse-grid {{
    grid-template-columns: repeat(2, 1fr);
  }}
}}

@media (max-width: 680px) {{
  .announcement__secondary {{
    display: none;
  }}

  .announcement__inner {{
    justify-content: center;
    text-align: center;
  }}

  .site-header {{
    min-height: 68px;
    padding-inline: 18px;
  }}

  .header-actions > a:first-child {{
    display: none;
  }}

  .page-shell {{
    width: min(calc(100% - 36px), var(--content));
  }}

  .hero {{
    min-height: auto;
    padding-block: 52px 72px;
  }}

  .hero h1 {{
    font-size: clamp(3rem, 15vw, 4.8rem);
  }}

  .hero-metrics {{
    grid-template-columns: 1fr;
  }}

  .hero-product {{
    min-height: 430px;
    padding: 20px;
  }}

  .headphone {{
    transform: scale(.78);
  }}

  .category-nav__inner {{
    padding-block: 20px;
    align-items: flex-start;
    flex-direction: column;
  }}

  .featured {{
    padding-block: 82px;
  }}

  .section-heading {{
    align-items: flex-start;
    flex-direction: column;
  }}

  .product-grid,
  .browse-grid {{
    grid-template-columns: 1fr;
  }}

  .product-card--lead {{
    grid-column: auto;
  }}

  .brand-story {{
    padding-block: 84px;
  }}

  .site-footer__inner {{
    padding-block: 48px;
    align-items: flex-start;
    flex-direction: column;
  }}
}}

@media (prefers-reduced-motion: reduce) {{
  html {{
    scroll-behavior: auto;
  }}

  *,
  *::before,
  *::after {{
    animation-duration: .01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: .01ms !important;
  }}
}}
'''

    @staticmethod
    def route_shell(
        brand_name: str,
        title: str,
        description: str,
        prefix: str,
        content: str,
    ) -> str:
        return f'''<!doctype html>
<html lang="vi">
<head>
  <meta charset="utf-8">
  <meta
    name="viewport"
    content="width=device-width, initial-scale=1"
  >
  <title>{html.escape(title)} — {html.escape(brand_name)}</title>
  <link rel="stylesheet" href="{prefix}assets/site.css">
</head>
<body>
  <header class="site-header">
    <a class="brand" href="{prefix}">
      <span class="brand__mark" aria-hidden="true">V</span>
      <span>{html.escape(brand_name)}</span>
    </a>

    <nav class="main-nav" aria-label="Điều hướng chính">
      <a href="{prefix}category/">Sản phẩm</a>
      <a href="{prefix}search/">Tìm kiếm</a>
      <a href="{prefix}cart/">Giỏ hàng</a>
    </nav>

    <div class="header-actions">
      <a href="{prefix}search/">Tìm kiếm</a>
      <a href="{prefix}cart/">Giỏ hàng</a>
    </div>
  </header>

  <main class="route-page page-shell">
    <header class="route-page__heading">
      <p class="section-kicker">{html.escape(brand_name)}</p>
      <h1>{html.escape(title)}</h1>
      <p>{html.escape(description)}</p>
    </header>

    {content}
  </main>

  <script src="{prefix}assets/site.js"></script>
</body>
</html>
'''

    @staticmethod
    def browse_content(
        prefix: str,
    ) -> str:
        products = [
            ("Aurora Headphones", "2.490.000₫", "aurora-headphones"),
            ("Arc Keyboard", "1.890.000₫", "arc-keyboard"),
            ("Luma Lamp", "1.290.000₫", "luma-lamp"),
            ("Flow Mouse", "990.000₫", "aurora-headphones"),
            ("Halo Stand", "790.000₫", "arc-keyboard"),
            ("Soft Dock", "690.000₫", "luma-lamp"),
        ]

        items = []

        for name, price, slug in products:
            items.append(
                (
                    '<article class="compact-product">'
                    f'<a href="{prefix}product/{slug}/">'
                    '<div class="compact-product__media"></div>'
                    f"<h3>{html.escape(name)}</h3>"
                    f"<p>{html.escape(price)}</p>"
                    "</a>"
                    "</article>"
                )
            )

        return (
            '<div class="browse-layout">'
            '<aside class="filter-panel">'
            "<h2>Bộ lọc</h2>"
            '<div class="filter-list">'
            "<span>Danh mục</span>"
            "<span>Khoảng giá</span>"
            "<span>Màu sắc</span>"
            "<span>Tình trạng</span>"
            "</div>"
            "</aside>"
            '<section class="browse-grid" aria-label="Danh sách sản phẩm">'
            + "".join(items)
            + "</section>"
            "</div>"
        )

    @staticmethod
    def transaction_content(
        mode: str,
    ) -> str:
        if mode == "cart":
            return (
                '<div class="transaction-layout">'
                '<section class="form-stack">'
                '<article class="summary">'
                "<strong>Aurora Headphones</strong>"
                "<p>1 × 2.490.000₫</p>"
                "</article>"
                '<article class="summary">'
                "<strong>Arc Keyboard</strong>"
                "<p>1 × 1.890.000₫</p>"
                "</article>"
                "</section>"
                '<aside class="summary">'
                "<h2>Tóm tắt đơn hàng</h2>"
                "<p>Tạm tính: 4.380.000₫</p>"
                "<p>Vận chuyển: Miễn phí</p>"
                "<strong>Tổng: 4.380.000₫</strong>"
                '<p><a class="button button--primary" '
                'href="../checkout/">Tiếp tục thanh toán</a></p>'
                "</aside>"
                "</div>"
            )

        return (
            '<div class="transaction-layout">'
            '<form class="form-stack">'
            '<div class="field">'
            '<label for="name">Họ và tên</label>'
            '<input id="name" name="name" autocomplete="name">'
            "</div>"
            '<div class="field">'
            '<label for="email">Email</label>'
            '<input id="email" name="email" type="email" '
            'autocomplete="email">'
            "</div>"
            '<div class="field">'
            '<label for="address">Địa chỉ giao hàng</label>'
            '<input id="address" name="address" '
            'autocomplete="street-address">'
            "</div>"
            '<button class="button button--primary" type="submit">'
            "Xác nhận đơn hàng"
            "</button>"
            "</form>"
            '<aside class="summary">'
            "<h2>Đơn hàng</h2>"
            "<p>Aurora Headphones</p>"
            "<p>Arc Keyboard</p>"
            "<strong>Tổng: 4.380.000₫</strong>"
            "</aside>"
            "</div>"
        )

    @staticmethod
    def product_content(
        name: str,
        price: str,
        prefix: str,
    ) -> str:
        return (
            '<div class="transaction-layout">'
            '<div class="hero-product">'
            '<div class="headphone" aria-hidden="true">'
            '<div class="headphone__band"></div>'
            '<div class="headphone__cup headphone__cup--left"></div>'
            '<div class="headphone__cup headphone__cup--right"></div>'
            "</div>"
            "</div>"
            '<aside class="summary">'
            f"<h2>{html.escape(name)}</h2>"
            f"<p><strong>{html.escape(price)}</strong></p>"
            "<p>Thiết kế tối giản, dễ sử dụng và phù hợp "
            "với không gian hiện đại.</p>"
            '<button class="button button--primary" type="button">'
            "Thêm vào giỏ"
            "</button>"
            '<p><a class="text-link" '
            f'href="{prefix}cart/">Xem giỏ hàng →</a></p>'
            "</aside>"
            "</div>"
        )

    @staticmethod
    def js() -> str:
        return (
            '"use strict";\n'
            'document.documentElement.dataset.renderer = "frontend-v2";\n'
        )

    @staticmethod
    def next_package() -> str:
        return json.dumps(
            {
                "name": "uiux-factory-generated-site",
                "version": "0.2.0",
                "private": True,
                "scripts": {
                    "dev": "next dev",
                    "build": "next build",
                    "publish:github": (
                        "next build && node scripts/publish-root.mjs"
                    ),
                },
                "dependencies": {
                    "next": "^15.5.0",
                    "react": "^19.1.0",
                    "react-dom": "^19.1.0",
                },
                "devDependencies": {
                    "@types/node": "^22.0.0",
                    "@types/react": "^19.0.0",
                    "@types/react-dom": "^19.0.0",
                    "typescript": "^5.8.0",
                },
            },
            indent=2,
        ) + "\n"

    @staticmethod
    def next_config() -> str:
        return '''const basePath =
  process.env.GITHUB_PAGES_BASE_PATH || "";

const nextConfig = {
  output: "export",
  trailingSlash: true,
  images: {
    unoptimized: true,
  },
  basePath,
  assetPrefix: basePath || undefined,
};

export default nextConfig;
'''

    @staticmethod
    def publish_script() -> str:
        return '''import {
  cp,
  writeFile,
} from "node:fs/promises";

import path from "node:path";
import {
  fileURLToPath,
} from "node:url";

const here = path.dirname(
  fileURLToPath(import.meta.url)
);

const appRoot = path.resolve(
  here,
  ".."
);

const outDir = path.join(
  appRoot,
  "out"
);

const publishRoot = path.resolve(
  appRoot,
  ".."
);

await cp(
  outDir,
  publishRoot,
  {
    recursive: true,
    force: true,
  }
);

await writeFile(
  path.join(
    publishRoot,
    ".nojekyll"
  ),
  "",
  "utf8"
);

console.log(
  `Static export copied to ${publishRoot}`
);
'''

    @staticmethod
    def next_layout() -> str:
        return '''import type {
  Metadata,
} from "next";

import Link from "next/link";

import "./globals.css";

export const metadata: Metadata = {
  title: "Violet Market",
  description:
    "Curated technology for modern living.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi">
      <body>
        <header className="site-header">
          <Link
            className="brand"
            href="/"
          >
            <span
              className="brand__mark"
              aria-hidden="true"
            >
              V
            </span>
            Violet
          </Link>

          <nav
            className="main-nav"
            aria-label="Điều hướng chính"
          >
            <Link href="/category/">
              Sản phẩm
            </Link>
            <Link href="/search/">
              Tìm kiếm
            </Link>
            <Link href="/cart/">
              Giỏ hàng
            </Link>
          </nav>
        </header>

        {children}
      </body>
    </html>
  );
}
'''

    @staticmethod
    def next_home() -> str:
        return '''import Link from "next/link";

export default function HomePage() {
  return (
    <main>
      <section className="hero page-shell">
        <div className="hero__content">
          <div className="eyebrow">
            <span className="eyebrow__line" />
            <span>Bộ sưu tập 2026</span>
          </div>

          <h1>
            Công nghệ đẹp hơn.
            <span>
              Trải nghiệm tốt hơn.
            </span>
          </h1>

          <p className="hero__description">
            Những sản phẩm được chọn lọc
            cho không gian sống và làm việc
            hiện đại.
          </p>

          <div className="hero__actions">
            <Link
              className="button button--primary"
              href="/category/"
            >
              Khám phá bộ sưu tập
            </Link>
          </div>
        </div>

        <div className="hero-product">
          <div
            className="headphone"
            aria-hidden="true"
          >
            <div className="headphone__band" />
            <div
              className={
                "headphone__cup " +
                "headphone__cup--left"
              }
            />
            <div
              className={
                "headphone__cup " +
                "headphone__cup--right"
              }
            />
          </div>
        </div>
      </section>
    </main>
  );
}
'''

    @staticmethod
    def next_simple_page(
        title: str,
        description: str,
    ) -> str:
        return f'''export default function Page() {{
  return (
    <main className="route-page page-shell">
      <header className="route-page__heading">
        <p className="section-kicker">
          Violet
        </p>
        <h1>{json.dumps(title, ensure_ascii=False)}</h1>
        <p>
          {json.dumps(description, ensure_ascii=False)}
        </p>
      </header>
    </main>
  );
}}
'''

    @staticmethod
    def next_tokens(
        brand: str,
    ) -> str:
        return f''':root {{
  --brand: {brand};
  --brand-900: #26133d;
  --brand-100: #efe8ff;
  --surface: #fcfbfd;
  --text: #17131d;
  --text-muted: #6d6675;
  --border: #e8e2ec;
  --content: 1320px;
}}
'''

    @staticmethod
    def next_globals() -> str:
        return '''@import "../styles/tokens.css";

* {
  box-sizing: border-box;
}

html {
  color: var(--text);
  background: var(--surface);
  font-family:
    Arial,
    Helvetica,
    sans-serif;
}

body {
  margin: 0;
}

a {
  color: inherit;
  text-decoration: none;
}

a:focus-visible,
button:focus-visible {
  outline: 3px solid var(--brand);
  outline-offset: 4px;
}

.page-shell {
  width: min(
    calc(100% - 56px),
    var(--content)
  );
  margin-inline: auto;
}

.site-header {
  max-width: var(--content);
  min-height: 78px;
  margin: 0 auto;
  padding-inline: 28px;
  display: flex;
  justify-content: space-between;
  align-items: center;
  border-bottom: 1px solid var(--border);
}

.brand,
.main-nav {
  display: flex;
  align-items: center;
}

.brand {
  gap: 10px;
  font-weight: 850;
}

.brand__mark {
  width: 32px;
  height: 32px;
  display: grid;
  place-items: center;
  border-radius: 50%;
  color: white;
  background: var(--brand);
}

.main-nav {
  gap: 28px;
}

.hero {
  min-height: 700px;
  padding-block: 72px;
  display: grid;
  grid-template-columns: .94fr 1.06fr;
  gap: 72px;
  align-items: center;
}

.eyebrow {
  color: var(--brand);
  font-size: .72rem;
  font-weight: 850;
  letter-spacing: .14em;
  text-transform: uppercase;
}

.hero h1 {
  margin: 24px 0 22px;
  font-size: clamp(
    3.45rem,
    5.8vw,
    6rem
  );
  line-height: .96;
  letter-spacing: -.064em;
}

.hero h1 span {
  display: block;
  color: var(--brand);
}

.hero__description {
  color: var(--text-muted);
  line-height: 1.75;
}

.button {
  min-height: 52px;
  padding-inline: 22px;
  display: inline-flex;
  align-items: center;
  border-radius: 14px;
  font-weight: 800;
}

.button--primary {
  color: white;
  background: var(--brand);
}

.hero-product {
  min-height: 560px;
  display: grid;
  place-items: center;
  border-radius: 30px;
  background: var(--brand-100);
}

.headphone {
  position: relative;
  width: 310px;
  height: 320px;
}

.headphone__band {
  position: absolute;
  left: 50%;
  top: 22px;
  width: 185px;
  height: 224px;
  transform: translateX(-50%);
  border: 30px solid var(--brand-900);
  border-bottom: 0;
  border-radius: 112px 112px 25px 25px;
}

.headphone__cup {
  position: absolute;
  bottom: 18px;
  width: 86px;
  height: 128px;
  border-radius: 45px;
  background: var(--brand);
}

.headphone__cup--left {
  left: 35px;
}

.headphone__cup--right {
  right: 35px;
}

.route-page {
  min-height: 70vh;
  padding-block: 88px;
}

.route-page__heading {
  max-width: 760px;
}

.section-kicker {
  color: var(--brand);
  font-size: .72rem;
  font-weight: 850;
}

@media (max-width: 760px) {
  .main-nav {
    display: none;
  }

  .page-shell {
    width: min(
      calc(100% - 36px),
      var(--content)
    );
  }

  .hero {
    min-height: auto;
    grid-template-columns: 1fr;
  }
}

@media (prefers-reduced-motion: reduce) {
  * {
    scroll-behavior: auto !important;
  }
}
'''

    @classmethod
    def policy_checks(
        cls,
        html_content: str,
        css_content: str,
        skills_loaded: int,
        visual_ready: bool,
    ) -> dict[str, bool]:
        lowered = html_content.lower()

        semantic = all(
            token in lowered
            for token in (
                "<header",
                "<nav",
                "<main",
                "<section",
                "<footer",
            )
        )

        technical_copy_absent = not any(
            term in lowered
            for term in cls.TECHNICAL_COPY
        )

        return {
            "required_skills_loaded": (
                skills_loaded >= 8
            ),
            "visual_composition_consumed": (
                visual_ready
            ),
            "semantic_html": semantic,
            "responsive_css": (
                "@media" in css_content
            ),
            "focus_visible": (
                ":focus-visible"
                in css_content
            ),
            "reduced_motion": (
                "prefers-reduced-motion"
                in css_content
            ),
            "technical_copy_absent": (
                technical_copy_absent
            ),
            "root_relative_static_links": (
                'href="./'
                in html_content
            ),
        }

    async def run(
        self,
        instruction: str,
    ) -> str:
        payload = json.loads(
            instruction
        )

        factory_root = Path(
            payload.get(
                "factory_root",
                "",
            )
        ).resolve()

        contract = (
            DesignContract
            .model_validate_json(
                payload.get(
                    "design_contract_content",
                    "",
                )
            )
        )

        design_system = (
            DesignSystemContract
            .model_validate_json(
                payload.get(
                    "design_system_content",
                    "",
                )
            )
        )

        plan = (
            ImplementationPlan
            .model_validate_json(
                payload.get(
                    "implementation_plan_content",
                    "",
                )
            )
        )

        composition = (
            VisualComposition
            .model_validate_json(
                payload.get(
                    "visual_composition_content",
                    "",
                )
            )
        )

        if not (
            plan.gates
            .ready_for_frontend_engineer
        ):
            raise RuntimeError(
                "Implementation Plan is not ready."
            )

        if not (
            composition.gates
            .ready_for_frontend_engineer
        ):
            raise RuntimeError(
                "Visual Composition is not ready."
            )

        if (
            composition.project_slug
            != plan.project_slug
        ):
            raise RuntimeError(
                "Visual Composition project does not "
                "match Implementation Plan."
            )

        policy_resolver = (
            SkillPolicyResolver()
        )

        policies = (
            policy_resolver
            .load_frontend_required()
        )

        home_spec = self.find_page(
            composition,
            "/",
        )

        self.require_home_contract(
            home_spec
        )

        writer = WorkspaceWriter(
            factory_root
        )

        project_slug = plan.project_slug

        project_root = (
            writer.project_root(
                project_slug
            )
        )

        brand, brand_status = (
            self.resolve_brand(
                design_system,
                contract,
            )
        )

        brand_name = "Violet"

        generated_files = []

        def write(
            relative_path: str,
            content: str,
            kind: str,
        ) -> None:
            path = writer.write_text(
                project_slug,
                relative_path,
                content,
            )

            generated_files.append(
                GeneratedFile(
                    path=str(
                        path.relative_to(
                            project_root
                        )
                    ).replace(
                        "\\",
                        "/",
                    ),
                    kind=kind,
                )
            )

        home_html = self.home_html(
            brand_name
        )

        css_content = self.css(
            brand
        )

        write(
            "index.html",
            home_html,
            "github-pages-entry",
        )

        write(
            "assets/site.css",
            css_content,
            "static-style",
        )

        write(
            "assets/site.js",
            self.js(),
            "static-script",
        )

        write(
            ".nojekyll",
            "",
            "github-pages-config",
        )

        self.find_page(
            composition,
            "/category",
        )
        self.find_page(
            composition,
            "/search",
        )
        self.find_page(
            composition,
            "/cart",
        )
        self.find_page(
            composition,
            "/checkout",
        )

        write(
            "category/index.html",
            self.route_shell(
                brand_name,
                "Sản phẩm",
                (
                    "Khám phá, lọc và so sánh "
                    "các sản phẩm được tuyển chọn."
                ),
                "../",
                self.browse_content(
                    "../"
                ),
            ),
            "github-pages-route",
        )

        write(
            "search/index.html",
            self.route_shell(
                brand_name,
                "Tìm kiếm",
                (
                    "Tìm sản phẩm nhanh "
                    "theo nhu cầu của bạn."
                ),
                "../",
                self.browse_content(
                    "../"
                ),
            ),
            "github-pages-route",
        )

        write(
            "cart/index.html",
            self.route_shell(
                brand_name,
                "Giỏ hàng",
                "Kiểm tra lựa chọn trước khi thanh toán.",
                "../",
                self.transaction_content(
                    "cart"
                ),
            ),
            "github-pages-route",
        )

        write(
            "checkout/index.html",
            self.route_shell(
                brand_name,
                "Thanh toán",
                "Hoàn tất đơn hàng với thông tin rõ ràng.",
                "../",
                self.transaction_content(
                    "checkout"
                ),
            ),
            "github-pages-route",
        )

        product_examples = [
            (
                "aurora-headphones",
                "Aurora Headphones",
                "2.490.000₫",
            ),
            (
                "arc-keyboard",
                "Arc Keyboard",
                "1.890.000₫",
            ),
            (
                "luma-lamp",
                "Luma Lamp",
                "1.290.000₫",
            ),
        ]

        for slug, name, price in product_examples:
            write(
                (
                    "product/"
                    f"{slug}/"
                    "index.html"
                ),
                self.route_shell(
                    brand_name,
                    name,
                    (
                        "Thiết kế rõ ràng để bạn "
                        "đánh giá sản phẩm trước khi mua."
                    ),
                    "../../",
                    self.product_content(
                        name,
                        price,
                        "../../",
                    ),
                ),
                "github-pages-route",
            )

        skills_evidence = [
            SkillEvidence(
                name=policy.name,
                relative_path=(
                    policy.relative_path
                ),
                sha256=policy.sha256,
                rule_count=len(
                    policy.rule_lines
                ),
            )
            for policy in policies
        ]

        skills_json = {
            "skills_root": str(
                policy_resolver.skills_root
            ),
            "skills": [
                {
                    "name": policy.name,
                    "path": (
                        policy.relative_path
                    ),
                    "sha256": (
                        policy.sha256
                    ),
                    "rule_count": len(
                        policy.rule_lines
                    ),
                    "sample_rules": (
                        policy.rule_lines[:8]
                    ),
                }
                for policy in policies
            ],
        }

        write(
            "skills-used.json",
            json.dumps(
                skills_json,
                indent=2,
                ensure_ascii=False,
            ),
            "skill-evidence",
        )

        write(
            "visual-composition.json",
            composition.model_dump_json(
                indent=2
            ),
            "composition-evidence",
        )

        manifest = {
            "renderer": "frontend-engineer-v2",
            "project_slug": project_slug,
            "reality": "prototype-mock-data",
            "brand": {
                "name": brand_name,
                "primary": brand,
                "primary_status": (
                    brand_status
                ),
            },
            "github_pages": {
                "entry": "index.html",
                "deploy_root": ".",
            },
            "next_app": "next-app",
        }

        write(
            "frontend-manifest.json",
            json.dumps(
                manifest,
                indent=2,
                ensure_ascii=False,
            ),
            "manifest",
        )

        next_files = {
            (
                "next-app/"
                "package.json"
            ): self.next_package(),
            (
                "next-app/"
                "next.config.mjs"
            ): self.next_config(),
            (
                "next-app/"
                "tsconfig.json"
            ): json.dumps(
                {
                    "compilerOptions": {
                        "target": "ES2017",
                        "lib": [
                            "dom",
                            "dom.iterable",
                            "esnext",
                        ],
                        "strict": True,
                        "noEmit": True,
                        "module": "esnext",
                        "moduleResolution": "bundler",
                        "resolveJsonModule": True,
                        "isolatedModules": True,
                        "jsx": "preserve",
                        "skipLibCheck": True,
                        "paths": {
                            "@/*": [
                                "./src/*"
                            ]
                        },
                        "plugins": [
                            {
                                "name": "next"
                            }
                        ],
                    },
                    "include": [
                        "next-env.d.ts",
                        "**/*.ts",
                        "**/*.tsx",
                        ".next/types/**/*.ts",
                    ],
                    "exclude": [
                        "node_modules"
                    ],
                },
                indent=2,
            ),
            (
                "next-app/"
                "next-env.d.ts"
            ): (
                '/// <reference types="next" />\n'
                '/// <reference types="next/image-types/global" />\n'
            ),
            (
                "next-app/"
                "src/styles/"
                "tokens.css"
            ): self.next_tokens(
                brand
            ),
            (
                "next-app/"
                "src/app/"
                "globals.css"
            ): self.next_globals(),
            (
                "next-app/"
                "src/app/"
                "layout.tsx"
            ): self.next_layout(),
            (
                "next-app/"
                "src/app/"
                "page.tsx"
            ): self.next_home(),
            (
                "next-app/"
                "src/app/"
                "category/"
                "page.tsx"
            ): self.next_simple_page(
                "Sản phẩm",
                (
                    "Khám phá, lọc và "
                    "so sánh sản phẩm."
                ),
            ),
            (
                "next-app/"
                "src/app/"
                "search/"
                "page.tsx"
            ): self.next_simple_page(
                "Tìm kiếm",
                "Tìm sản phẩm theo nhu cầu.",
            ),
            (
                "next-app/"
                "src/app/"
                "cart/"
                "page.tsx"
            ): self.next_simple_page(
                "Giỏ hàng",
                "Kiểm tra lựa chọn của bạn.",
            ),
            (
                "next-app/"
                "src/app/"
                "checkout/"
                "page.tsx"
            ): self.next_simple_page(
                "Thanh toán",
                "Hoàn tất đơn hàng.",
            ),
            (
                "next-app/"
                "scripts/"
                "publish-root.mjs"
            ): self.publish_script(),
        }

        for relative_path, content in (
            next_files.items()
        ):
            write(
                relative_path,
                content,
                "next-source",
            )

        checks = self.policy_checks(
            home_html,
            css_content,
            len(policies),
            (
                composition.gates
                .ready_for_frontend_engineer
            ),
        )

        if not all(
            checks.values()
        ):
            failed = [
                name
                for name, passed
                in checks.items()
                if not passed
            ]

            raise RuntimeError(
                "Frontend v2 policy gate failed: "
                f"{failed}"
            )

        unresolved = list(
            design_system
            .unresolved_items
        )

        unresolved.append(
            (
                f"Brand primary uses {brand} "
                f"with status {brand_status}."
            )
        )

        result = FrontendResult(
            status="generated",
            project_slug=project_slug,
            project_dir=str(
                project_root
            ),
            github_pages_entry=str(
                project_root
                / "index.html"
            ),
            next_app_dir=str(
                project_root
                / "next-app"
            ),
            files=generated_files,
            skills_used=skills_evidence,
            policy_checks=checks,
            commands=[
                (
                    f"cd {project_root / 'next-app'}"
                ),
                "npm install",
                "npm run dev",
                (
                    "$env:GITHUB_PAGES_BASE_PATH="
                    '"/REPOSITORY"; '
                    "npm run publish:github"
                ),
            ],
            unresolved_items=unresolved,
            gates=FrontendBuildGate(
                workspace_guardrail_passed=True,
                root_index_created=(
                    project_root
                    / "index.html"
                ).exists(),
                github_pages_static_tree_created=(
                    project_root
                    / "assets"
                    / "site.css"
                ).exists(),
                next_source_created=(
                    project_root
                    / "next-app"
                    / "package.json"
                ).exists(),
                visual_composition_consumed=True,
                required_skills_loaded=(
                    checks[
                        "required_skills_loaded"
                    ]
                ),
                semantic_html_passed=(
                    checks[
                        "semantic_html"
                    ]
                ),
                responsive_contract_passed=(
                    checks[
                        "responsive_css"
                    ]
                ),
                focus_contract_passed=(
                    checks[
                        "focus_visible"
                    ]
                ),
                technical_copy_gate_passed=(
                    checks[
                        "technical_copy_absent"
                    ]
                ),
                ready_for_dependency_install=True,
                build_verified=False,
            ),
        )

        return result.model_dump_json(
            indent=2
        )
