import html
import json
from pathlib import Path

from metagpt.actions import Action

from core.contracts.design_system_schema import (
    DesignSystemContract,
)
from core.contracts.frontend_result_schema import (
    FrontendBuildGate,
    FrontendResult,
    GeneratedFile,
)
from core.contracts.implementation_plan_schema import (
    ImplementationPlan,
)
from core.contracts.schema import DesignContract
from core.runtime.workspace_writer import WorkspaceWriter


class GenerateFrontendProject(Action):
    name: str = "GenerateFrontendProject"

    desc: str = (
        "Generate guarded frontend source plus a deployable "
        "outer index.html for GitHub Pages."
    )

    @staticmethod
    def resolve_brand(
        design_system: DesignSystemContract,
        contract: DesignContract,
    ) -> tuple[str, str]:
        token = design_system.foundations.colors.get(
            "color.brand.primary"
        )

        if token and token.value:
            return str(token.value), token.status

        family = (
            contract.project.requested_primary_color
            or ""
        ).lower()

        fallback = {
            "purple": "#6D28D9",
            "orange": "#EA7C16",
            "red": "#C62828",
            "green": "#168A4A",
            "blue": "#2563EB",
            "black": "#111116",
        }.get(family, "#6D28D9")

        return fallback, "factory_default"

    @staticmethod
    def static_index(brand: str) -> str:
        return f'''<!doctype html>
<html lang="vi">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="description" content="Generated by UIUX Factory">
  <title>Violet Market</title>
  <link rel="stylesheet" href="./assets/site.css">
</head>
<body>
  <header class="header">
    <a class="brand" href="./">Violet Market</a>
    <nav>
      <a href="./category/">Danh mục</a>
      <a href="./search/">Tìm kiếm</a>
      <a href="./cart/">Giỏ hàng</a>
    </nav>
  </header>

  <main class="shell">
    <section class="hero">
      <div>
        <p class="eyebrow">ECOMMERCE EXPERIENCE</p>
        <h1>Khám phá sản phẩm theo cách rõ ràng hơn.</h1>
        <p class="lede">
          Static GitHub Pages entry generated from the same
          canonical contracts used by the Next.js source.
        </p>
        <div class="actions">
          <a class="button primary" href="./category/">
            Khám phá sản phẩm
          </a>
          <a class="button secondary" href="./search/">
            Tìm kiếm
          </a>
        </div>
      </div>

      <div class="stage">
        <div class="glow"></div>
        <strong>AURA</strong>
        <span>Factory placeholder product</span>
      </div>
    </section>

    <section class="section">
      <div class="section-head">
        <h2>Sản phẩm nổi bật</h2>
        <p>
          Dữ liệu đang là deterministic placeholder,
          chưa phải dữ liệu thương mại thật.
        </p>
      </div>

      <div class="grid">
        <a class="product" href="./product/aurora-headphones/">
          <div class="media one"></div>
          <h3>Aurora Headphones</h3>
          <p>2.490.000₫</p>
        </a>

        <a class="product" href="./product/arc-keyboard/">
          <div class="media two"></div>
          <h3>Arc Keyboard</h3>
          <p>1.890.000₫</p>
        </a>

        <a class="product" href="./product/luma-lamp/">
          <div class="media three"></div>
          <h3>Luma Lamp</h3>
          <p>1.290.000₫</p>
        </a>
      </div>
    </section>
  </main>

  <script src="./assets/site.js"></script>
</body>
</html>
'''

    @staticmethod
    def static_css(brand: str) -> str:
        return f'''/* Brand value is a factory fallback until confirmed. */
:root {{
  --brand: {brand};
  --surface: #ffffff;
  --subtle: #f7f7fa;
  --text: #111116;
  --muted: #666672;
  --border: #e8e8ee;
  --content: 1200px;
}}

* {{ box-sizing: border-box; }}

html {{
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  background: var(--surface);
  color: var(--text);
}}

body {{
  margin: 0;
  min-height: 100vh;
  background:
    radial-gradient(circle at 80% 10%, color-mix(in srgb, var(--brand) 13%, white), transparent 30rem),
    var(--surface);
}}

a {{
  color: inherit;
  text-decoration: none;
}}

.header {{
  max-width: var(--content);
  margin: 0 auto;
  padding: 22px 24px;
  display: flex;
  justify-content: space-between;
  gap: 24px;
  border-bottom: 1px solid var(--border);
}}

.brand {{
  font-weight: 900;
  letter-spacing: -.04em;
}}

nav {{
  display: flex;
  gap: 22px;
  color: var(--muted);
}}

.shell {{
  max-width: var(--content);
  margin: 0 auto;
  padding: 72px 24px 96px;
}}

.hero {{
  display: grid;
  grid-template-columns: 1.05fr .95fr;
  gap: 64px;
  align-items: center;
}}

.eyebrow {{
  color: var(--brand);
  font-weight: 800;
  letter-spacing: .12em;
  font-size: .74rem;
}}

h1 {{
  margin: 12px 0 18px;
  font-size: clamp(3rem, 7vw, 6.4rem);
  line-height: .95;
  letter-spacing: -.065em;
}}

.lede {{
  max-width: 650px;
  color: var(--muted);
  line-height: 1.7;
}}

.actions {{
  display: flex;
  gap: 12px;
  flex-wrap: wrap;
  margin-top: 28px;
}}

.button {{
  min-height: 48px;
  display: inline-flex;
  align-items: center;
  padding: 0 20px;
  border-radius: 10px;
  font-weight: 800;
}}

.primary {{
  background: var(--brand);
  color: white;
}}

.secondary {{
  border: 1px solid var(--border);
  background: white;
}}

.stage {{
  min-height: 440px;
  position: relative;
  overflow: hidden;
  display: grid;
  place-items: center;
  background: #111116;
  color: white;
}}

.stage strong {{
  position: relative;
  font-size: clamp(4rem, 11vw, 8rem);
  letter-spacing: -.08em;
}}

.stage span {{
  position: absolute;
  left: 24px;
  bottom: 22px;
  color: #d6d6de;
}}

.glow {{
  width: 390px;
  height: 390px;
  position: absolute;
  border-radius: 50%;
  background: var(--brand);
  filter: blur(36px);
  opacity: .5;
}}

.section {{
  margin-top: 110px;
}}

.section-head {{
  display: flex;
  justify-content: space-between;
  gap: 30px;
  align-items: end;
  margin-bottom: 28px;
}}

.section-head h2 {{
  margin: 0;
  font-size: clamp(2rem, 4vw, 3.2rem);
  letter-spacing: -.045em;
}}

.section-head p {{
  max-width: 440px;
  color: var(--muted);
}}

.grid {{
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 18px;
}}

.product {{
  padding-top: 18px;
  border-top: 1px solid var(--border);
}}

.product h3 {{
  margin: 16px 0 6px;
}}

.product p {{
  margin: 0;
  color: var(--muted);
}}

.media {{
  aspect-ratio: 4 / 5;
  background: var(--subtle);
}}

.one {{
  background:
    radial-gradient(circle at 50% 45%, var(--brand) 0 18%, transparent 19%),
    #f2eefc;
}}

.two {{
  background:
    linear-gradient(145deg, transparent 28%, var(--brand) 29% 44%, transparent 45%),
    #f5f5f7;
}}

.three {{
  background:
    radial-gradient(ellipse at 50% 65%, var(--brand) 0 13%, transparent 14%),
    #eeeaf9;
}}

.page {{
  max-width: var(--content);
  margin: 0 auto;
  padding: 72px 24px 96px;
}}

.panel {{
  margin-top: 34px;
  padding: 24px;
  border: 1px solid var(--border);
  background: white;
}}

@media (max-width: 760px) {{
  .hero,
  .grid {{
    grid-template-columns: 1fr;
  }}

  .section-head {{
    align-items: start;
    flex-direction: column;
  }}

  .stage {{
    min-height: 320px;
  }}
}}
'''

    @staticmethod
    def static_js() -> str:
        return (
            'document.documentElement.dataset.uiuxFactory = "generated";\n'
            'console.info("UIUX Factory GitHub Pages build loaded.");\n'
        )

    @staticmethod
    def static_route(
        title: str,
        description: str,
        prefix: str,
        content: str,
    ) -> str:
        return f'''<!doctype html>
<html lang="vi">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>{html.escape(title)} · Violet Market</title>
  <link rel="stylesheet" href="{prefix}assets/site.css">
</head>
<body>
  <header class="header">
    <a class="brand" href="{prefix}">Violet Market</a>
    <nav>
      <a href="{prefix}category/">Danh mục</a>
      <a href="{prefix}search/">Tìm kiếm</a>
      <a href="{prefix}cart/">Giỏ hàng</a>
    </nav>
  </header>

  <main class="page">
    <p class="eyebrow">PAGE ROLE</p>
    <h1>{html.escape(title)}</h1>
    <p class="lede">{html.escape(description)}</p>
    {content}
  </main>

  <script src="{prefix}assets/site.js"></script>
</body>
</html>
'''

    @staticmethod
    def package_json() -> str:
        return json.dumps(
            {
                "name": "uiux-factory-generated-site",
                "version": "0.1.0",
                "private": True,
                "scripts": {
                    "dev": "next dev",
                    "build": "next build",
                    "publish:github": (
                        "next build && node scripts/publish-root.mjs"
                    ),
                },
                "dependencies": {
                    "next": "^15.5.0",
                    "react": "^19.1.0",
                    "react-dom": "^19.1.0",
                },
                "devDependencies": {
                    "@types/node": "^22.0.0",
                    "@types/react": "^19.0.0",
                    "@types/react-dom": "^19.0.0",
                    "typescript": "^5.8.0",
                },
            },
            indent=2,
        ) + "\n"

    @staticmethod
    def next_config() -> str:
        return '''const basePath =
  process.env.GITHUB_PAGES_BASE_PATH || "";

const nextConfig = {
  output: "export",
  trailingSlash: true,
  images: {
    unoptimized: true,
  },
  basePath,
  assetPrefix: basePath || undefined,
};

export default nextConfig;
'''

    @staticmethod
    def tsconfig() -> str:
        return '''{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": false,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx",
    ".next/types/**/*.ts"
  ],
  "exclude": ["node_modules"]
}
'''

    @staticmethod
    def next_tokens(brand: str) -> str:
        return f''':root {{
  --brand: {brand};
  --surface: #ffffff;
  --surface-subtle: #f7f7fa;
  --text-primary: #111116;
  --text-muted: #666672;
  --border-default: #e8e8ee;
  --layout-content: 1200px;
}}
'''

    @staticmethod
    def next_globals() -> str:
        return '''@import "../styles/tokens.css";

* {
  box-sizing: border-box;
}

html,
body {
  margin: 0;
}

body {
  color: var(--text-primary);
  background: var(--surface);
  font-family: Arial, Helvetica, sans-serif;
}

a {
  color: inherit;
  text-decoration: none;
}

.shell {
  max-width: var(--layout-content);
  margin: 0 auto;
  padding: 24px;
}

.hero {
  padding: 84px 0;
  display: grid;
  grid-template-columns: 1.05fr .95fr;
  gap: 56px;
  align-items: center;
}

.hero h1 {
  margin: 0;
  font-size: clamp(3rem, 7vw, 6.2rem);
  line-height: .95;
  letter-spacing: -.065em;
}

.stage {
  min-height: 420px;
  background: #111116;
  color: white;
  display: grid;
  place-items: center;
  font-size: clamp(4rem, 11vw, 8rem);
  font-weight: 900;
  letter-spacing: -.08em;
}

.grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 18px;
}

.card {
  border-top: 1px solid var(--border-default);
  padding-top: 18px;
}

.button {
  display: inline-flex;
  padding: 14px 18px;
  border-radius: 10px;
  background: var(--brand);
  color: white;
  font-weight: 700;
}

@media (max-width: 760px) {
  .hero,
  .grid {
    grid-template-columns: 1fr;
  }
}
'''

    @staticmethod
    def next_layout() -> str:
        return '''import type { Metadata } from "next";
import Link from "next/link";

import "./globals.css";

export const metadata: Metadata = {
  title: "Violet Market",
  description: "Generated by UIUX Factory",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi">
      <body>
        <header
          className="shell"
          style={{
            display: "flex",
            justifyContent: "space-between",
            borderBottom: "1px solid var(--border-default)",
          }}
        >
          <Link href="/" style={{ fontWeight: 900 }}>
            Violet Market
          </Link>
          <nav style={{ display: "flex", gap: 18 }}>
            <Link href="/category/">Danh mục</Link>
            <Link href="/search/">Tìm kiếm</Link>
            <Link href="/cart/">Giỏ hàng</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
'''

    @staticmethod
    def next_home() -> str:
        return '''import Link from "next/link";

export default function HomePage() {
  return (
    <main className="shell">
      <section className="hero">
        <div>
          <p
            style={{
              color: "var(--brand)",
              fontWeight: 800,
            }}
          >
            ECOMMERCE EXPERIENCE
          </p>

          <h1>
            Khám phá sản phẩm theo cách rõ ràng hơn.
          </h1>

          <p
            style={{
              color: "var(--text-muted)",
              lineHeight: 1.7,
            }}
          >
            Generated from Design Contract,
            Design System and Implementation Plan.
          </p>

          <Link
            href="/category/"
            className="button"
          >
            Khám phá sản phẩm
          </Link>
        </div>

        <div className="stage">
          AURA
        </div>
      </section>

      <section>
        <h2>Sản phẩm nổi bật</h2>
        <div className="grid">
          {["Aurora Headphones", "Arc Keyboard", "Luma Lamp"].map(
            (name) => (
              <article className="card" key={name}>
                <div
                  style={{
                    aspectRatio: "4 / 5",
                    background: "var(--surface-subtle)",
                  }}
                />
                <h3>{name}</h3>
                <p>Factory placeholder</p>
              </article>
            )
          )}
        </div>
      </section>
    </main>
  );
}
'''

    @staticmethod
    def simple_next_page(
        title: str,
        description: str,
    ) -> str:
        return f'''export default function Page() {{
  return (
    <main className="shell">
      <section style={{{{ padding: "72px 0" }}}}>
        <p style={{{{ color: "var(--brand)", fontWeight: 800 }}}}>
          PAGE ROLE
        </p>
        <h1>{json.dumps(title, ensure_ascii=False)}</h1>
        <p style={{{{ color: "var(--text-muted)" }}}}>
          {json.dumps(description, ensure_ascii=False)}
        </p>
      </section>
    </main>
  );
}}
'''


    @staticmethod
    def next_products() -> str:
        return """export const products = [
  {
    slug: "aurora-headphones",
    name: "Aurora Headphones",
    price: "2.490.000₫",
  },
  {
    slug: "arc-keyboard",
    name: "Arc Keyboard",
    price: "1.890.000₫",
  },
  {
    slug: "luma-lamp",
    name: "Luma Lamp",
    price: "1.290.000₫",
  },
];
"""

    @staticmethod
    def next_product_page() -> str:
        return """import { notFound } from "next/navigation";

import { products } from "@/lib/products";

export function generateStaticParams() {
  return products.map((product) => ({
    slug: product.slug,
  }));
}

export default async function ProductPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;

  const product = products.find(
    (item) => item.slug === slug
  );

  if (!product) {
    notFound();
  }

  return (
    <main className="shell">
      <section className="hero">
        <div className="stage">
          {product.name.slice(0, 4).toUpperCase()}
        </div>

        <div>
          <p
            style={{
              color: "var(--brand)",
              fontWeight: 800,
            }}
          >
            PRODUCT DETAIL
          </p>

          <h1
            style={{
              fontSize: "clamp(3rem, 6vw, 5rem)",
            }}
          >
            {product.name}
          </h1>

          <p
            style={{
              color: "var(--text-muted)",
            }}
          >
            Product decision composition generated
            from the Implementation Plan.
          </p>

          <p style={{ fontWeight: 800 }}>
            {product.price}
          </p>

          <button className="button">
            Thêm vào giỏ
          </button>
        </div>
      </section>
    </main>
  );
}
"""

    @staticmethod
    def publish_script() -> str:
        return '''import { cp, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(
  fileURLToPath(import.meta.url)
);

const appRoot = path.resolve(
  here,
  ".."
);

const outDir = path.join(
  appRoot,
  "out"
);

const publishRoot = path.resolve(
  appRoot,
  ".."
);

await cp(
  outDir,
  publishRoot,
  {
    recursive: true,
    force: true,
  }
);

await writeFile(
  path.join(publishRoot, ".nojekyll"),
  "",
  "utf8"
);

console.log(
  `Next static export copied to ${publishRoot}`
);
'''

    @staticmethod
    def github_pages_readme() -> str:
        return '''# GitHub Pages

The outer generated project folder is intentionally deployable as-is.

It already contains:

- `index.html`
- `assets/`
- static route folders
- `.nojekyll`

The Next.js source lives in `next-app/`.

To regenerate the outer static files from Next.js:

```powershell
cd .\\next-app
npm install
npm run publish:github
```

For a project page such as:

`https://USERNAME.github.io/REPOSITORY/`

use:

```powershell
$env:GITHUB_PAGES_BASE_PATH="/REPOSITORY"
npm run publish:github
```

For a custom domain or `USERNAME.github.io`, leave the base path empty.
'''

    async def run(
        self,
        instruction: str,
    ) -> str:
        payload = json.loads(instruction)

        factory_root = Path(
            payload.get(
                "factory_root",
                "",
            )
        ).resolve()

        plan = ImplementationPlan.model_validate_json(
            payload.get(
                "implementation_plan_content",
                "",
            )
        )

        contract = DesignContract.model_validate_json(
            payload.get(
                "design_contract_content",
                "",
            )
        )

        design_system = (
            DesignSystemContract.model_validate_json(
                payload.get(
                    "design_system_content",
                    "",
                )
            )
        )

        if not (
            plan.gates.ready_for_frontend_engineer
        ):
            raise RuntimeError(
                "Implementation Plan is not ready."
            )

        writer = WorkspaceWriter(factory_root)
        project_slug = plan.project_slug
        project_root = writer.project_root(
            project_slug
        )

        brand, brand_status = self.resolve_brand(
            design_system,
            contract,
        )

        files = []

        def write(
            relative_path: str,
            content: str,
            kind: str,
        ) -> None:
            path = writer.write_text(
                project_slug,
                relative_path,
                content,
            )

            files.append(
                GeneratedFile(
                    path=str(
                        path.relative_to(
                            project_root
                        )
                    ).replace("\\\\", "/"),
                    kind=kind,
                )
            )

        # GitHub Pages outer static tree.
        write(
            "index.html",
            self.static_index(brand),
            "github-pages-entry",
        )
        write(
            "assets/site.css",
            self.static_css(brand),
            "static-style",
        )
        write(
            "assets/site.js",
            self.static_js(),
            "static-script",
        )
        write(
            ".nojekyll",
            "",
            "github-pages-config",
        )

        routes = [
            (
                "category/index.html",
                "../",
                "Danh mục sản phẩm",
                "Browse / filter / compare composition.",
                '<div class="panel">Bộ lọc + danh sách sản phẩm</div>',
            ),
            (
                "search/index.html",
                "../",
                "Tìm kiếm",
                "Search-led composition.",
                '<div class="panel">Ô tìm kiếm + kết quả</div>',
            ),
            (
                "cart/index.html",
                "../",
                "Giỏ hàng",
                "Transactional composition.",
                '<div class="panel">Aurora Headphones · 2.490.000₫</div>',
            ),
            (
                "checkout/index.html",
                "../",
                "Thanh toán",
                "Focused checkout composition.",
                '<div class="panel">Thông tin giao hàng + order summary</div>',
            ),
        ]

        for (
            path,
            prefix,
            title,
            description,
            content,
        ) in routes:
            write(
                path,
                self.static_route(
                    title,
                    description,
                    prefix,
                    content,
                ),
                "github-pages-route",
            )

        for slug, name in [
            ("aurora-headphones", "Aurora Headphones"),
            ("arc-keyboard", "Arc Keyboard"),
            ("luma-lamp", "Luma Lamp"),
        ]:
            write(
                f"product/{slug}/index.html",
                self.static_route(
                    name,
                    "Product decision composition.",
                    "../../",
                    (
                        '<div class="panel">'
                        f'<h2>{html.escape(name)}</h2>'
                        '<p>Factory placeholder product.</p>'
                        '<a class="button primary" href="../../cart/">'
                        "Thêm vào giỏ</a>"
                        "</div>"
                    ),
                ),
                "github-pages-route",
            )

        write(
            "GITHUB_PAGES.md",
            self.github_pages_readme(),
            "documentation",
        )

        write(
            "frontend-manifest.json",
            json.dumps(
                {
                    "project_slug": project_slug,
                    "brand": {
                        "value": brand,
                        "status": brand_status,
                    },
                    "github_pages_entry": "index.html",
                    "next_app": "next-app",
                },
                indent=2,
                ensure_ascii=False,
            ),
            "manifest",
        )

        # Next.js source, isolated from deployable static root.
        next_files = {
            "next-app/package.json": self.package_json(),
            "next-app/next.config.mjs": self.next_config(),
            "next-app/tsconfig.json": self.tsconfig(),
            "next-app/next-env.d.ts": (
                '/// <reference types="next" />\n'
                '/// <reference types="next/image-types/global" />\n'
            ),
            "next-app/src/styles/tokens.css": (
                self.next_tokens(brand)
            ),
            "next-app/src/app/globals.css": (
                self.next_globals()
            ),
            "next-app/src/app/layout.tsx": (
                self.next_layout()
            ),
            "next-app/src/app/page.tsx": (
                self.next_home()
            ),
            "next-app/src/app/category/page.tsx": (
                self.simple_next_page(
                    "Danh mục sản phẩm",
                    "Browse / filter / compare composition.",
                )
            ),
            "next-app/src/app/search/page.tsx": (
                self.simple_next_page(
                    "Tìm kiếm",
                    "Search-led composition.",
                )
            ),
            "next-app/src/app/cart/page.tsx": (
                self.simple_next_page(
                    "Giỏ hàng",
                    "Transactional composition.",
                )
            ),
            "next-app/src/app/checkout/page.tsx": (
                self.simple_next_page(
                    "Thanh toán",
                    "Focused checkout composition.",
                )
            ),
            "next-app/src/lib/products.ts": (
                self.next_products()
            ),
            "next-app/src/app/product/[slug]/page.tsx": (
                self.next_product_page()
            ),
            "next-app/scripts/publish-root.mjs": (
                self.publish_script()
            ),
        }

        for (
            relative_path,
            content,
        ) in next_files.items():
            write(
                relative_path,
                content,
                "next-source",
            )

        unresolved = list(
            design_system.unresolved_items
        )

        unresolved.append(
            (
                f"Brand primary currently uses {brand} "
                f"with status {brand_status}."
            )
        )

        result = FrontendResult(
            status="generated",
            project_slug=project_slug,
            project_dir=str(project_root),
            github_pages_entry=str(
                project_root / "index.html"
            ),
            next_app_dir=str(
                project_root / "next-app"
            ),
            files=files,
            commands=[
                (
                    f"cd {project_root / 'next-app'}"
                ),
                "npm install",
                "npm run dev",
                (
                    "$env:GITHUB_PAGES_BASE_PATH="
                    '"/REPOSITORY"; npm run publish:github'
                ),
            ],
            unresolved_items=unresolved,
            gates=FrontendBuildGate(
                workspace_guardrail_passed=True,
                root_index_created=(
                    project_root / "index.html"
                ).exists(),
                github_pages_static_tree_created=(
                    project_root
                    / "assets"
                    / "site.css"
                ).exists(),
                next_source_created=(
                    project_root
                    / "next-app"
                    / "package.json"
                ).exists(),
                ready_for_dependency_install=True,
                build_verified=False,
            ),
        )

        return result.model_dump_json(
            indent=2
        )
