from datetime import datetime

from metagpt.actions import Action

from core.skills.loader import SkillLoader


class ResearchCompetitors(Action):
    name: str = "ResearchCompetitors"
    desc: str = "Prepare UI/UX research brief from skills_UIUX."

    async def run(self, instruction: str) -> str:
        loader = SkillLoader()

        stats = loader.stats()

        selected_skills = loader.select(limit=6)

        if selected_skills:
            skills_markdown = "\n".join(
                f"- `{skill.relative_path}` "
                f"(score: {skill.score})"
                for skill in selected_skills
            )
        else:
            skills_markdown = "- No matching skill found."

        created_at = datetime.now().isoformat(
            timespec="seconds"
        )

        return f"""# UI/UX Research Brief

## Goal

{instruction}

## Execution

- Mode: `mock`
- Created: `{created_at}`
- LLM API used: `no`
- External research: `not executed`
- skills_UIUX: `{stats["skills_root"]}`
- Skills discovered: `{stats["skill_count"]}`

## Selected skills

{skills_markdown}

## Research objectives

1. Understand business model and target users.
2. Identify direct competitors.
3. Identify strong UX benchmark products.
4. Analyze information architecture.
5. Analyze visual direction.
6. Analyze conversion patterns.
7. Detect generic AI-looking UI patterns.
8. Produce constraints for design.

## Evidence Gate

Status: `PENDING`

Mock mode does not claim any external competitor,
trend or market information has been verified.

## Next outputs required

- verified competitors
- source URLs
- screenshots
- UX observations
- visual observations
- reusable patterns
- patterns to avoid
- IA implications
- art direction implications

---

Generated by ResearchAgent.
"""